version: "3"

services:
  api-gateway:
    image: api-gateway
    ports:
      - "8090:8090"
    volumes:
      - "/data"
    networks:
      - default
      - mynetwork
networks:
  mynetwork:
    external: true


